Repository mdbootstrap/TW-Elements, pull requests merged in 2023-12, with the labels that each got.

#2192 Add v1.1.0 changelog
  site/content/docs/standard/getting-started/changelog/index-ss.html
  site/content/docs/standard/getting-started/changelog/index.html
Labels: cla-signed

#2175 Add bun instructions
  site/content/docs/standard/getting-started/quick-start/index-ss.html
  site/content/docs/standard/getting-started/quick-start/index.html
Labels: cla-signed

#2218 Add license comments to snippets Clipboard
  site/content/docs/standard/getting-started/quick-start/index.html
  site/static/js/new-prism.js
Labels: cla-signed

#2030 Fix #1949 Done updating default text color to #4f4f4f through classes
  site/assets/css/main.css
  src/scss/tailwind.scss
Labels: cla-signed, MAJOR

#2220 added license restrictions
  site/content/docs/standard/getting-started/quick-start/index.html
  site/layouts/partials/header/header.html
Labels: cla-signed

#2222 changed icon and bg-color in quick start
  site/content/docs/standard/getting-started/quick-start/index.html
Labels: cla-signed

#2170 Update tooltip and popover template customization
  site/content/docs/standard/components/popover/a.html
  site/content/docs/standard/components/tooltip/a.html
  src/js/components/popover.js
  src/js/components/tooltip.js
  src/js/util/sanitizer.js
Labels: cla-signed, MAJOR, CR

#2252 Update files/index.html file that goes into built package
  src/files/index.html
Labels: cla-signed, CR
